### ISSUE TITLE
Akumuli will not compile on Clang 3.6

### ISSUE THREAD

**Issue by facontidavide** [akumuli/Akumuli#100]
I am trying to compile on Ubuntu 14.04 with Clang 3.6.

Nope...

/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;

**Comment by Lazin** [comment]
You should install libstdc++ and use it with clang (pass -stdlib=libc++ option to the compiler). There is  no clang support in my cmake scripts but  you can easily add this option when invoking cmake: 
> cmake /path/to/src -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_FLAGS_RELEASE="${CMAKE_CXX_FLAGS_RELEASE} -stdlib=libc++"
