### ISSUE TITLE
compilation error at Ubuntu 15.10

### ISSUE THREAD

**Issue by zstyblik** [akumuli/Akumuli#77]
Hello,

I'm getting the following compilation error at Ubuntu 15.10. Please, do you have any thoughts what's wrong? I've tried master, v0.3.0 and v0.2.0, but all end up the same. So I guess I'm missing some library/header files?

```
stybla@akumuli:~/Akumuli$ cmake .
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   unit_test_framework
--   program_options
--   system
--   thread
--   filesystem
--   coroutine
--   context
--   regex
--   date_time
-- Found log4cxx: /usr/lib/x86_64-linux-gnu/liblog4cxx.so
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found Sqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Found APR headers: /usr/include/apr-1.0
-- Found APR library: /usr/lib/x86_64-linux-gnu/libapr-1.so
-- Found APRUTIL headers: /usr/include/apr-1.0
-- Found APRUTIL library: /usr/lib/x86_64-linux-gnu/libaprutil-1.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stybla/Akumuli
stybla@akumuli:~/Akumuli$ make
[  1%] Building CXX object libakumuli/CMakeFiles/akumuli.dir/storage.cpp.o
In file included from /home/stybla/Akumuli/libakumuli/page.h:30:0,
                 from /home/stybla/Akumuli/libakumuli/storage.h:38,
                 from /home/stybla/Akumuli/libakumuli/storage.cpp:19:
/home/stybla/Akumuli/libakumuli/internal_cursor.h:36:29: error: ‘caller_type’ in ‘Akumuli::Coroutine {aka struct boost::coroutines::coroutine<void(Akumuli::InternalCursor*)>}’ does not name a type
 typedef typename Coroutine::caller_type Caller;
                             ^
libakumuli/CMakeFiles/akumuli.dir/build.make:77: recipe for target 'libakumuli/CMakeFiles/akumuli.dir/storage.cpp.o' failed
make[2]: *** [libakumuli/CMakeFiles/akumuli.dir/storage.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'libakumuli/CMakeFiles/akumuli.dir/all' failed
make[1]: *** [libakumuli/CMakeFiles/akumuli.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you.

**Comment by Lazin** [comment]
Everything should work with boost 1.54. In newer versions of boost.coroutine they removed bidirectional coroutines (they are deprecated in 1.54). I'm planing to move akumuli to newer version of boost libraries but at the moment it will be easier to use older version of boost.

**Comment by zstyblik** [comment]
I see. Sadly, I don't have time to do such thing right now. Even Debian Jessie comes with 1.55 and there seems to be no point in trying out Wheezy.

Thank you for the reply, though, and Merry Christmas.
